### ISSUE TITLE
Update features to the latest Wazuh versions

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-salt#2]
Hello world,

This repository has been outdated for years, so it'd be convenient to update each component to the latest stable versions:

- [x] https://github.com/wazuh/wazuh-salt/issues/1 Update agents formulas.
- [x] Update manager formulas.
- [x] Updated ELK formulas.
- [x] Write docs.

Regards
